import type { DemoConfig } from "../types";

// Iron Wolf Ranch & Distillery — concept demo.
// Brand facts, products, cocktails, and places on the property come from
// public info. EVERY person, account, band, guest truck, and number is
// invented. Phones use the fictional 555-01XX range; emails use example.com.

export const ironwolf: DemoConfig = {
  slug: "ironwolf",
  seed: 0x1f0f17,
  timeZone: "America/Chicago",
  company: {
    name: "Iron Wolf Ranch & Distillery",
    wordmark: ["IRON WOLF", "RANCH & DISTILLERY"],
    appName: "Pack HQ",
    place: "Spicewood, TX",
    teamName: "the pack",
  },
  // Sampled from ironwolfranch.com: charcoal #231f20, amber #eeac35, and
  // the brushed-steel header. Dark UI like their site's stone sections.
  theme: {
    bg: "#161314",
    panel: "#231f20",
    panel2: "#2e292a",
    line: "#3d3738",
    text: "#f4efe8",
    muted: "#b9b0a8",
    accent: "#eeac35",
    onAccent: "#231f20",
    good: "#7cc47f",
    bad: "#ff7a6e",
    warn: "#f2a65a",
    steel: ["#e4e4e1", "#b4b5b1"],
  },
  copy: {
    ribbon:
      "Sample data. Concept demo built for Iron Wolf Ranch & Distillery by Rose Revenue. All names, accounts and numbers are fictional.",
    banner: "Concept built for Iron Wolf using public info and fictional data. Click anything.",
    closing: {
      title: "This is what yours could look like.",
      paragraphs: [
        "Everything here is sample data. The real version runs on your actual reports: distributor depletions, your ranch point of sale, your event calendar, the maintenance list that lives in someone's head right now.",
        "It starts with a 2–3 week assessment, where I learn how the pack really works. Then we build it together. You own the code and the data, and nobody gets replaced. The jobs just get easier.",
      ],
    },
  },
  modules: [
    { key: "overview", label: "Overview", icon: "home", path: "" },
    { key: "crm", label: "CRM", icon: "users", path: "crm" },
    { key: "kpis", label: "Scorecard", icon: "gauge", path: "kpis" },
    { key: "sales", label: "Sales", icon: "chart", path: "sales" },
    { key: "ranch", label: "Ranch", icon: "ranch", path: "ranch" },
    { key: "maintenance", label: "Maintenance", icon: "wrench", path: "maintenance" },
    { key: "projects", label: "Projects", icon: "board", path: "projects" },
  ],
  people: [
    { id: "ceo", name: "Russ Kettering", role: "CEO & President" },
    { id: "ops", name: "Marisol Vega", role: "VP Operations & Head Distiller" },
    { id: "mkt", name: "Tanner Boyce", role: "VP Marketing & Events" },
    { id: "gm", name: "Cody Lindqvist", role: "Ranch GM" },
    { id: "events", name: "Brooke Haddad", role: "Events Coordinator" },
    { id: "tasting", name: "Jolene Park", role: "Tasting Room Lead" },
    { id: "maint", name: "Hector Ruiz", role: "Maintenance Lead" },
    { id: "bottling", name: "Dwayne Pruitt", role: "Bottling Lead" },
    { id: "cigar", name: "Silas Monroe", role: "Cigar Lounge Manager" },
  ],
  reps: [
    { id: "rep-atx", name: "Kasey Brandt", role: "Market Manager, Austin/Hill Country & San Antonio" },
    { id: "rep-waco", name: "Luis Ocampo", role: "Market Manager, North Austin & Waco and DFW" },
    { id: "rep-hou", name: "Denise Whitford", role: "Market Manager, Houston" },
    { id: "rep-arla", name: "Grant Thibodeaux", role: "Market Manager, Arkansas & Louisiana" },
    { id: "rep-fl", name: "Renee Castellano", role: "Market Manager, Florida" },
  ],
  markets: [
    { id: "atx", name: "Austin/Hill Country", state: "TX", areaCode: "512", cities: ["Austin", "Spicewood", "Marble Falls", "Dripping Springs", "Lakeway", "Bee Cave"], accounts: 42, repId: "rep-atx" },
    { id: "waco", name: "North Austin & Waco", state: "TX", areaCode: "254", cities: ["Waco", "Round Rock", "Georgetown", "Temple", "Belton"], accounts: 22, repId: "rep-waco" },
    { id: "sat", name: "San Antonio", state: "TX", areaCode: "210", cities: ["San Antonio", "New Braunfels", "Boerne", "San Marcos"], accounts: 26, repId: "rep-atx" },
    { id: "hou", name: "Houston", state: "TX", areaCode: "713", cities: ["Houston", "The Woodlands", "Katy", "Sugar Land", "Galveston"], accounts: 32, repId: "rep-hou" },
    { id: "dfw", name: "DFW", state: "TX", areaCode: "214", cities: ["Dallas", "Fort Worth", "Denton", "Frisco", "Arlington"], accounts: 28, repId: "rep-waco" },
    { id: "nwa", name: "NW Arkansas", state: "AR", areaCode: "479", cities: ["Fayetteville", "Bentonville", "Rogers", "Springdale"], accounts: 11, repId: "rep-arla" },
    { id: "lr", name: "Little Rock", state: "AR", areaCode: "501", cities: ["Little Rock", "North Little Rock", "Conway"], accounts: 9, repId: "rep-arla" },
    { id: "nola", name: "New Orleans", state: "LA", areaCode: "504", cities: ["New Orleans", "Metairie", "Kenner"], accounts: 14, repId: "rep-arla" },
    { id: "br", name: "Baton Rouge", state: "LA", areaCode: "225", cities: ["Baton Rouge", "Denham Springs", "Gonzales"], accounts: 8, repId: "rep-arla" },
    { id: "tpa", name: "Tampa Bay", state: "FL", areaCode: "813", cities: ["Tampa", "St. Petersburg", "Clearwater", "Brandon"], accounts: 15, repId: "rep-fl" },
    { id: "cfl", name: "Central Florida", state: "FL", areaCode: "407", cities: ["Orlando", "Kissimmee", "Winter Park", "Sanford"], accounts: 13, repId: "rep-fl" },
  ],
  skus: [
    { id: "hotscotch", name: "Hotscotch", kind: "Butterscotch-pepper whiskey", casePrice: 168, bottlePrice: 29.99, weight: 3.2, season: "cold", channel: "all" },
    { id: "hotscotch50", name: "Hotscotch 50ml", kind: "Minis", casePrice: 158, bottlePrice: 3.99, weight: 1.0, season: "cold", channel: "all" },
    { id: "ironhot", name: "Iron Hot", kind: "Cinnamon-pepper whiskey", casePrice: 168, bottlePrice: 29.99, weight: 2.2, season: "cold", channel: "all" },
    { id: "ironhot50", name: "Iron Hot 50ml", kind: "Minis", casePrice: 158, bottlePrice: 3.99, weight: 0.7, season: "cold", channel: "all" },
    { id: "bourbon", name: "Select Bourbon", kind: "Bourbon", casePrice: 252, bottlePrice: 44.99, weight: 1.3, season: "flat", channel: "all" },
    { id: "rye", name: "Straight Rye", kind: "Rye whiskey · limited", casePrice: 288, bottlePrice: 54.99, weight: 0.5, season: "flat", channel: "limited" },
    { id: "giddyup", name: "Giddy'Up!", kind: "Horseradish vodka", casePrice: 132, bottlePrice: 24.99, weight: 0.8, season: "flat", channel: "all" },
    { id: "gin", name: "Gin", kind: "Gin", casePrice: 156, bottlePrice: 27.99, weight: 0.9, season: "warm", channel: "all" },
    { id: "vodka", name: "Vodka", kind: "Vodka", casePrice: 120, bottlePrice: 22.99, weight: 1.2, season: "warm", channel: "all" },
    { id: "rum", name: "Barrel-aged Rum", kind: "Ranch exclusive", casePrice: 0, bottlePrice: 39.99, weight: 0, season: "flat", channel: "ranch" },
  ],
  accountTypes: [
    { type: "Bar", share: 0.3, size: 1, skus: ["hotscotch", "ironhot", "vodka", "giddyup", "gin", "bourbon"] },
    { type: "Restaurant", share: 0.22, size: 0.9, skus: ["hotscotch", "bourbon", "giddyup", "gin", "vodka"] },
    { type: "Package store", share: 0.25, size: 1.7, skus: ["hotscotch", "hotscotch50", "ironhot", "ironhot50", "bourbon", "vodka", "gin"] },
    { type: "Regional grocery", share: 0.08, size: 2.6, skus: ["hotscotch", "hotscotch50", "ironhot", "ironhot50", "vodka"] },
    { type: "Venue", share: 0.08, size: 1.4, skus: ["hotscotch", "ironhot", "vodka", "bourbon"] },
    { type: "Hotel", share: 0.07, size: 1.1, skus: ["bourbon", "hotscotch", "gin", "vodka"] },
  ],
  sales: {
    monthlyCasesBase: 830,
    //            Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
    seasonIndex: [1.1, 1.03, 0.95, 0.93, 0.92, 0.95, 0.94, 0.9, 0.97, 1.08, 1.2, 1.24],
    txShare: 0.8,
    growthPerMonth: 0.006,
  },
  ranch: {
    openHours: { fri: [16, 17, 18, 19], sat: [12, 13, 14, 15, 16, 17, 18, 19] },
    stages: ["Main Stage", "Bourbon Garden Stage", "The Den"],
    houseTruck: "Hungry Wolf",
    guestTrucks: ["Mesquite & Masa", "The Kolache Cart", "Pit Stop Smokehouse", "Sweet Clover Pies", "Brisket Bandit", "Taco Tumbleweed", "Gulf Coast Po'boys"],
    acts: [
      "The Caliche Kings", "Dust Road Revival", "Hannah Rae & the Tin Roof", "Mesquite Hymnal", "The Low Water Crossing",
      "Rattler Radio", "June Harlan Band", "Two-Step Syndicate", "The Pecan Pickers", "Cody Vance & the Norther",
      "Big Sky Bandits", "The Saltwell Sisters", "Highway 71 Revue", "Luke Arden Trio", "Brass Buckle Brass Band",
      "Wren & the Wildflowers", "Gravel Road Gospel", "The Longneck Lullabies", "Sierra Blanca Swing", "Pedernales Drifters",
    ],
    cocktails: [
      { name: "Wolf Pack Old Fashioned", price: 14, weight: 1.6 },
      { name: "Hotscotch Texas Sour", price: 13, weight: 1.9 },
      { name: "Hill Country Haze", price: 12, weight: 1.1 },
      { name: "Big Tex", price: 13, weight: 0.9 },
      { name: "Texas 75", price: 13, weight: 0.8 },
      { name: "Giddy'Up! Mary", price: 12, weight: 0.9 },
      { name: "Howlin' at the Mule", price: 12, weight: 1.3 },
      { name: "Iron Hot Toddy", price: 12, weight: 0.6 },
      { name: "Peach Spring Fling", price: 12, weight: 0.7 },
      { name: "Lonestar Lemonade", price: 11, weight: 1.2 },
      { name: "Spicewood Spring Julep", price: 13, weight: 0.6 },
      { name: "Good Mojo Mojito", price: 12, weight: 0.8 },
      { name: "Iron Werewolf", price: 14, weight: 0.7 },
      { name: "Berry Smash", price: 11, weight: 0.8 },
    ],
    eventTypes: [
      { type: "Wedding", guests: [90, 220], price: [9000, 22000] },
      { type: "Corporate", guests: [40, 150], price: [4500, 12000] },
      { type: "Fundraiser", guests: [80, 240], price: [5000, 14000] },
      { type: "Bach party", guests: [12, 30], price: [1800, 4200] },
      { type: "Birthday", guests: [25, 80], price: [2500, 6000] },
    ],
    eventHosts: ["Alder Ridge Title", "Hollis Engineering", "Cypress Bend Rotary", "Lakeshore Dental Group", "Quarry Road Realty", "Bluebonnet Animal Rescue", "Twin Oaks Builders", "Sandpiper Credit Union"],
    //            Jan  Feb  Mar  Apr  May  Jun   Jul   Aug  Sep   Oct  Nov   Dec
    visitorSeason: [0.72, 0.8, 1.08, 1.18, 1.1, 0.95, 0.88, 0.82, 0.96, 1.2, 1.06, 0.94],
  },
  kpis: [
    { key: "txCases", name: "TX cases shipped", owner: "ceo", direction: "atLeast", unit: "cases" },
    { key: "oosCases", name: "Out-of-state cases shipped", owner: "rep-arla", direction: "atLeast", unit: "cases" },
    { key: "newAccounts", name: "New accounts placed", owner: "ceo", direction: "atLeast", unit: "count" },
    { key: "visits", name: "Account visits completed", owner: "rep-atx", direction: "atLeast", unit: "count" },
    { key: "tastings", name: "Tastings & activations run", owner: "mkt", direction: "atLeast", unit: "count" },
    { key: "bottleShop", name: "Bottle shop sales", owner: "tasting", direction: "atLeast", unit: "money" },
    { key: "ranchCocktails", name: "Ranch cocktail sales", owner: "gm", direction: "atLeast", unit: "money" },
    { key: "ranchFoodCigar", name: "Ranch food + cigar sales", owner: "gm", direction: "atLeast", unit: "money" },
    { key: "privateEvents", name: "Private events booked", owner: "events", direction: "atLeast", unit: "count" },
    { key: "newsletter", name: "Newsletter signups", owner: "mkt", direction: "atLeast", unit: "count" },
    { key: "production", name: "Production runs bottled", owner: "ops", direction: "atLeast", unit: "count" },
    { key: "openMaintenance", name: "Open maintenance items", owner: "maint", direction: "atMost", unit: "count" },
  ],
  maintenance: {
    locations: ["Still House", "The Den", "Stages & Bourbon Garden", "Grounds & Playground", "Cigar Lounge", "Barrel Storage"],
    items: [
      { title: "Boiler relief valve inspection", equipment: "Steam boiler", location: "Still House", priority: "High" },
      { title: "Column still gasket weeping at plate 4", equipment: "Column still", location: "Still House", priority: "Critical" },
      { title: "Glycol chiller making grinding noise", equipment: "Glycol chiller", location: "Still House", priority: "High" },
      { title: "Labeler misfeeds on 750ml run", equipment: "Bottling line labeler", location: "Still House", priority: "High" },
      { title: "Mash tun agitator seal replacement", equipment: "Mash tun", location: "Still House", priority: "Medium" },
      { title: "Grain auger jamming on startup", equipment: "Grain auger", location: "Still House", priority: "Medium" },
      { title: "Condenser water line leak check", equipment: "Condenser", location: "Still House", priority: "Low" },
      { title: "Walk-in cooler door seal torn", equipment: "Walk-in cooler", location: "The Den", priority: "High" },
      { title: "Ice machine descale", equipment: "Ice machine", location: "The Den", priority: "Medium" },
      { title: "Bar sink draining slow", equipment: "Back bar sink", location: "The Den", priority: "Low" },
      { title: "Stage lights dimmer flicker", equipment: "Lighting dimmer", location: "The Den", priority: "Medium" },
      { title: "HVAC filter swap", equipment: "Rooftop HVAC", location: "The Den", priority: "Low" },
      { title: "Main stage PA crackle on left main", equipment: "PA system", location: "Stages & Bourbon Garden", priority: "High" },
      { title: "Fire pit gas line pressure test", equipment: "Fire pit #3", location: "Stages & Bourbon Garden", priority: "Critical" },
      { title: "String lights out over garden seating", equipment: "String lights", location: "Stages & Bourbon Garden", priority: "Low" },
      { title: "Stage roof tarp tear", equipment: "Bourbon Garden stage", location: "Stages & Bourbon Garden", priority: "Medium" },
      { title: "Drip irrigation zone 2 not running", equipment: "Irrigation controller", location: "Stages & Bourbon Garden", priority: "Low" },
      { title: "Well pump pressure dropping", equipment: "Well pump", location: "Grounds & Playground", priority: "Critical" },
      { title: "Septic pump-out", equipment: "Septic system", location: "Grounds & Playground", priority: "Medium" },
      { title: "Fence repair along back pasture", equipment: "Perimeter fence", location: "Grounds & Playground", priority: "Medium" },
      { title: "Gravel regrade in overflow parking", equipment: "Parking lot", location: "Grounds & Playground", priority: "Low" },
      { title: "Playground swing chain worn", equipment: "Swing set", location: "Grounds & Playground", priority: "High" },
      { title: "Golf cart battery won't hold charge", equipment: "Golf cart #2", location: "Grounds & Playground", priority: "Low" },
      { title: "Humidor calibration off by 6%", equipment: "Walk-in humidor", location: "Cigar Lounge", priority: "High" },
      { title: "Smoke eater fan bearing squeal", equipment: "Smoke eater", location: "Cigar Lounge", priority: "Medium" },
      { title: "AC condensate line clog", equipment: "Mini-split", location: "Cigar Lounge", priority: "Medium" },
      { title: "Barrel storage humidity running low", equipment: "Humidistat", location: "Barrel Storage", priority: "High" },
      { title: "Forklift annual service", equipment: "Forklift", location: "Barrel Storage", priority: "Medium" },
      { title: "Rack bolt torque check", equipment: "Barrel racks", location: "Barrel Storage", priority: "Low" },
      { title: "Roll-up door sensor intermittent", equipment: "Roll-up door", location: "Barrel Storage", priority: "Medium" },
    ],
  },
  projects: [
    {
      id: "concerts", name: "Fall Concert Series", anchor: { month: 10, day: 17 },
      items: [
        { name: "Confirm three headliners", owner: "mkt", group: "Done", status: "Done", priority: "High", start: -60, due: -32 },
        { name: "Sound & lighting contract", owner: "gm", group: "Done", status: "Done", priority: "High", start: -45, due: -25 },
        { name: "Poster + social artwork", owner: "mkt", group: "This week", status: "Working on it", priority: "Medium", start: -10, due: 3 },
        { name: "Ticket page & presale email", owner: "mkt", group: "This week", status: "Working on it", priority: "High", start: -6, due: 5 },
        { name: "Parking & shuttle plan", owner: "gm", group: "Up next", status: "Not started", priority: "Medium", start: 4, due: 18 },
        { name: "Security staffing", owner: "gm", group: "Up next", status: "Stuck", priority: "High", start: -3, due: 12 },
        { name: "Headliner cocktail specials", owner: "tasting", group: "Up next", status: "Not started", priority: "Low", start: 8, due: 22 },
        { name: "Rain plan: move to The Den", owner: "events", group: "Up next", status: "Not started", priority: "Medium", start: 10, due: 24 },
      ],
    },
    {
      id: "arla", name: "Arkansas & Louisiana Distributor Onboarding",
      items: [
        { name: "Distributor agreement signed", owner: "ceo", group: "Done", status: "Done", priority: "Critical", start: -80, due: -50 },
        { name: "State label registrations", owner: "ops", group: "Done", status: "Done", priority: "High", start: -70, due: -30 },
        { name: "Price postings (AR)", owner: "rep-arla", group: "This week", status: "Working on it", priority: "High", start: -8, due: 4 },
        { name: "Sales deck for distributor reps", owner: "mkt", group: "This week", status: "Working on it", priority: "Medium", start: -5, due: 6 },
        { name: "Ride-alongs: New Orleans", owner: "rep-arla", group: "Up next", status: "Not started", priority: "Medium", start: 7, due: 21 },
        { name: "Ride-alongs: NW Arkansas", owner: "rep-arla", group: "Up next", status: "Not started", priority: "Medium", start: 14, due: 28 },
        { name: "Launch-order allocation", owner: "ops", group: "Up next", status: "Stuck", priority: "High", start: -2, due: 10 },
      ],
    },
    {
      id: "rye", name: "Rye Label Refresh",
      items: [
        { name: "Design round 1 feedback", owner: "mkt", group: "Done", status: "Done", priority: "Medium", start: -40, due: -26 },
        { name: "Design round 2", owner: "mkt", group: "This week", status: "Working on it", priority: "Medium", start: -9, due: 2 },
        { name: "Federal label approval submission", owner: "ops", group: "Up next", status: "Not started", priority: "High", start: 3, due: 12 },
        { name: "Printer proof & paper stock", owner: "ops", group: "Up next", status: "Not started", priority: "Medium", start: 12, due: 26 },
        { name: "Update bottle shop shelf talker", owner: "tasting", group: "Up next", status: "Not started", priority: "Low", start: 26, due: 34 },
      ],
    },
    {
      id: "minis", name: "Holiday 50ml Minis Gift Set", anchor: { month: 11, day: 15 },
      items: [
        { name: "Gift box dieline approved", owner: "mkt", group: "Done", status: "Done", priority: "High", start: -50, due: -35 },
        { name: "Packaging supplier order", owner: "ops", group: "This week", status: "Stuck", priority: "Critical", start: -20, due: -2 },
        { name: "Retailer sell sheet", owner: "mkt", group: "This week", status: "Working on it", priority: "Medium", start: -6, due: 4 },
        { name: "Allocate minis by market", owner: "ceo", group: "Up next", status: "Not started", priority: "High", start: 2, due: 14 },
        { name: "Bottling run: Hotscotch 50ml", owner: "bottling", group: "Up next", status: "Not started", priority: "High", start: 9, due: 16 },
        { name: "Bottling run: Iron Hot 50ml", owner: "bottling", group: "Up next", status: "Not started", priority: "High", start: 16, due: 23 },
        { name: "Bottle shop display", owner: "tasting", group: "Up next", status: "Not started", priority: "Low", start: 30, due: 40 },
      ],
    },
    {
      id: "veterans", name: "Veterans Day Celebration prep", anchor: { month: 11, day: 11 },
      items: [
        { name: "Honor guard + anthem singer confirmed", owner: "events", group: "This week", status: "Working on it", priority: "High", start: -12, due: 3 },
        { name: "Free admission & tasting for veterans", owner: "gm", group: "Done", status: "Done", priority: "Medium", start: -30, due: -18 },
        { name: "Partner with local VFW post", owner: "events", group: "This week", status: "Working on it", priority: "Medium", start: -8, due: 6 },
        { name: "Commemorative cocktail", owner: "tasting", group: "Up next", status: "Not started", priority: "Low", start: 6, due: 20 },
        { name: "Flag line along the drive", owner: "maint", group: "Up next", status: "Not started", priority: "Low", start: 20, due: 30 },
        { name: "Press release", owner: "mkt", group: "Up next", status: "Not started", priority: "Medium", start: 10, due: 25 },
      ],
    },
  ],
  names: {
    first: [
      "Dana", "Luis", "Priya", "Walt", "June", "Cole", "Mara", "Travis", "Nina", "Beau", "Tessa", "Ramon", "Whitney", "Jace",
      "Carmen", "Dillon", "Hallie", "Mateo", "Paige", "Wade", "Lena", "Garrett", "Rosa", "Colby", "Ines", "Hank", "Shelby",
      "Omar", "Kendra", "Reid", "Lucia", "Brody", "Maggie", "Andre", "Tori", "Emmett", "Yesenia", "Clint", "Avery", "Nico",
      "Darla", "Tate", "Marisa", "Boone", "Kira", "Felix", "Jolie", "Rhett", "Sasha", "Dom",
    ],
    last: [
      "Alvarez", "Whitman", "Pruett", "Nguyen", "Holloway", "Castillo", "Brennan", "Okafor", "Delacroix", "Sutter", "Villanueva",
      "Kessler", "Marsh", "Talley", "Oyelaran", "Guidry", "Ferris", "Lockhart", "Benavides", "Quinlan", "Rourke", "Stroud",
      "Hebert", "Mendel", "Calloway", "Tran", "Pickens", "Ybarra", "Dunaway", "Fontenot", "Harlan", "Esparza", "Winslow",
      "Keel", "Landry", "Morrow", "Salcedo", "Pettit", "Rangel", "Bishop",
    ],
    venueStems: [
      "Copperjack", "Mesquite Owl", "Two Spur", "Cedar Hollow", "Redbird", "Caliche", "Blue Norther", "Pecan Hollow", "Sotol",
      "Buckshot", "Brass Buckle", "Whistlestop", "Lucky Lasso", "Prickly Pear", "Dry Creek", "Low Water", "Limestone",
      "Rattler", "Lantern Hill", "Hitching Post", "Sawtooth", "Bluebonnet", "Grackle", "Armadillo Moon", "Starlight Ranch",
      "Cypress Bend", "Crawdad", "Bayou Lantern", "Magnolia Porch", "Pelican Dock", "Saltmarsh", "Palmetto", "Mango Pier",
      "Ozark Hollow", "Razor Ridge", "Riverstone", "Hollowpine", "Quarry Road", "Oak Motte", "Windmill", "Gallows Oak",
      "Tin Star", "Silver Spur", "Fox & Fiddle", "Honey Locust", "Cattle Guard", "Longneck", "Dust Devil", "Sidewinder",
      "Bois d'Arc", "Juniper Flat", "Red River", "Cane Brake", "Heron Point", "Driftwood", "Mockingbird", "Black Kettle",
    ],
    suffixes: {
      Bar: ["Icehouse", "Saloon", "Tavern", "Tap Room", "Social Club", "Lounge", "Beer Garden"],
      Restaurant: ["Kitchen", "Grill", "Smokehouse", "Cantina", "Supper Club", "Bistro"],
      "Package store": ["Wine & Spirits", "Liquor", "Bottle Shop", "Package Store", "Spirits"],
      "Regional grocery": ["Market", "Grocers", "Fresh Market", "Food Co."],
      Venue: ["Dance Hall", "Music Hall", "Event Barn", "Ballroom"],
      Hotel: ["Hotel", "Inn", "Lodge", "Resort"],
    },
  },
};
