// Seed data for the Sweet Grass Dairy concept demo. Product lines, prices and
// farm facts follow the farm's public store and site; every person, customer,
// account, animal name and record here is invented. Phones are 555-01XX,
// emails are @example.com.

import type { FarmSeed, SkuSeed } from "@/lib/demo/farm/types";

const GRILL = [0.8, 0.8, 0.9, 1, 1.2, 1.35, 1.4, 1.3, 1.1, 1, 0.9, 1.1];
const STEW = [1.3, 1.3, 1.1, 0.9, 0.7, 0.6, 0.6, 0.7, 0.9, 1.2, 1.3, 1.3];
const BUNDLE = [0.6, 0.5, 0.5, 0.6, 0.6, 0.6, 0.6, 0.7, 1, 2.3, 2.5, 2];
const BIRD = [0.8, 0.8, 0.9, 1, 1.1, 1.2, 1.2, 1.2, 1.1, 1, 0.9, 0.8];
const HOLIDAY = [1, 1, 1.05, 1.15, 1, 1, 1, 1, 1, 1, 1.15, 1.25];

const skus: SkuSeed[] = [
  // Stock your freezer
  { id: "b-fall", name: "Fall Freezer Bundle", category: "Stock your freezer", enterprise: "beef", source: "bundle", unit: "bundle, ~20 lb", price: 249, lbs: 20, pop: 1.1, season: BUNDLE, par: 0, frozen: true,
    components: { "beef-ground": 10, "beef-chuck": 1, "beef-stew": 2, "beef-ribeye": 1, "beef-strip": 1, "beef-shortrib": 1, "beef-bones": 1 } },
  { id: "b-grill", name: "Grill Master Bundle", category: "Stock your freezer", enterprise: "beef", source: "bundle", unit: "bundle, ~9 lb", price: 169, lbs: 9, pop: 0.6, season: GRILL, par: 0, frozen: true,
    components: { "beef-ribeye": 2, "beef-strip": 2, "beef-ground": 4, "beef-filet": 1 } },
  { id: "b-staples", name: "Family Staples Bundle", category: "Stock your freezer", enterprise: "beef", source: "bundle", unit: "bundle, ~15 lb", price: 149, lbs: 15, pop: 0.7, season: BUNDLE, par: 0, frozen: true,
    components: { "beef-ground": 6, "pork-chops": 2, "pork-sausage": 2, "chx-whole": 1, "pork-bacon": 1 } },
  { id: "b-quarter", name: "Quarter-Share Beef Box", category: "Stock your freezer", enterprise: "beef", source: "bundle", unit: "box, ~40 lb", price: 559, lbs: 40, pop: 0.22, season: BUNDLE, par: 0, frozen: true,
    components: { "beef-ground": 20, "beef-chuck": 2, "beef-ribeye": 3, "beef-strip": 3, "beef-filet": 1, "beef-stew": 3, "beef-shortrib": 2, "beef-bones": 2 } },

  // Grass-fed beef (yieldPer = packages per steer)
  { id: "beef-ribeye", name: "Ribeye steak", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "pkg, ~0.9 lb", price: 33.3, perLb: 37, lbs: 0.9, pop: 2, season: GRILL, par: 40, frozen: true, wholesale: true, yieldPer: 24 },
  { id: "beef-strip", name: "NY strip steak", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "pkg, ~0.85 lb", price: 25.93, perLb: 30.5, lbs: 0.85, pop: 1.6, season: GRILL, par: 36, frozen: true, wholesale: true, yieldPer: 22 },
  { id: "beef-filet", name: "Filet mignon", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "pkg, ~0.5 lb", price: 22.75, perLb: 45.5, lbs: 0.5, pop: 1.2, season: HOLIDAY, par: 20, frozen: true, yieldPer: 12 },
  { id: "beef-ground", name: "Ground beef", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "1 lb pkg", price: 13.65, perLb: 13.65, lbs: 1, pop: 4, par: 220, frozen: true, wholesale: true, yieldPer: 170 },
  { id: "beef-chuck", name: "Chuck roast", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "pkg, ~2.5 lb", price: 37.5, perLb: 15, lbs: 2.5, pop: 1.1, season: STEW, par: 24, frozen: true, yieldPer: 12 },
  { id: "beef-shortrib", name: "Short ribs", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "pkg, ~1.5 lb", price: 19.5, perLb: 13, lbs: 1.5, pop: 0.9, season: STEW, par: 20, frozen: true, wholesale: true, yieldPer: 10 },
  { id: "beef-stew", name: "Stew meat", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "1 lb pkg", price: 14.5, perLb: 14.5, lbs: 1, pop: 1.5, season: STEW, par: 30, frozen: true, yieldPer: 20 },
  { id: "beef-bones", name: "Soup bones", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "pkg, ~1.5 lb", price: 7.5, perLb: 5, lbs: 1.5, pop: 0.7, season: STEW, par: 20, frozen: true, yieldPer: 16 },
  { id: "beef-fat", name: "Beef fat (suet)", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "pkg, ~2 lb", price: 5.2, perLb: 2.6, lbs: 2, pop: 0.35, par: 12, frozen: true, yieldPer: 10 },
  { id: "beef-liver", name: "Beef liver", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "1 lb pkg", price: 8, perLb: 8, lbs: 1, pop: 0.45, par: 10, frozen: true, yieldPer: 8 },
  { id: "beef-jerky", name: "Beef jerky", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "4 oz bag", price: 12, lbs: 0.25, pop: 2.6, par: 30, yieldPer: 9 },
  { id: "beef-sticks", name: "Beef snack sticks", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "6-pack", price: 9, lbs: 0.4, pop: 2.6, par: 30, yieldPer: 7 },
  { id: "beef-summer", name: "Summer sausage", category: "Grass-fed beef", enterprise: "beef", source: "beef", unit: "12 oz log", price: 14, lbs: 0.75, pop: 1.7, season: HOLIDAY, par: 16, yieldPer: 5 },

  // Pastured pork (per hog)
  { id: "pork-chops", name: "Pork chops", category: "Pastured pork", enterprise: "pork", source: "pork", unit: "1 lb pkg", price: 14, perLb: 14, lbs: 1, pop: 1, season: GRILL, par: 30, frozen: true, wholesale: true, yieldPer: 20 },
  { id: "pork-bacon", name: "Bacon", category: "Pastured pork", enterprise: "pork", source: "pork", unit: "1 lb pkg", price: 15, perLb: 15, lbs: 1, pop: 1.3, par: 40, frozen: true, wholesale: true, yieldPer: 16 },
  { id: "pork-sausage", name: "Breakfast sausage", category: "Pastured pork", enterprise: "pork", source: "pork", unit: "1 lb pkg", price: 11, perLb: 11, lbs: 1, pop: 1.1, par: 40, frozen: true, yieldPer: 34 },
  { id: "pork-shoulder", name: "Pork shoulder roast", category: "Pastured pork", enterprise: "pork", source: "pork", unit: "pkg, ~3 lb", price: 30, perLb: 10, lbs: 3, pop: 0.55, season: STEW, par: 10, frozen: true, yieldPer: 6 },
  { id: "pork-ham", name: "Smoked ham, half", category: "Pastured pork", enterprise: "pork", source: "pork", unit: "~5 lb", price: 45, perLb: 9, lbs: 5, pop: 0.4, season: HOLIDAY, par: 6, frozen: true, yieldPer: 2 },

  // Lamb (per lamb)
  { id: "lamb-chops", name: "Lamb loin chops", category: "Lamb", enterprise: "lamb", source: "lamb", unit: "1 lb pkg", price: 28, perLb: 28, lbs: 1, pop: 0.8, par: 12, frozen: true, yieldPer: 6 },
  { id: "lamb-ground", name: "Ground lamb", category: "Lamb", enterprise: "lamb", source: "lamb", unit: "1 lb pkg", price: 15, perLb: 15, lbs: 1, pop: 1, par: 16, frozen: true, yieldPer: 14 },
  { id: "lamb-leg", name: "Leg of lamb", category: "Lamb", enterprise: "lamb", source: "lamb", unit: "~4 lb", price: 68, perLb: 17, lbs: 4, pop: 0.3, season: HOLIDAY, par: 4, frozen: true, yieldPer: 2 },

  // Poultry (yieldPer = packages per bird processed)
  { id: "chx-whole", name: "Whole chicken", category: "Poultry", enterprise: "poultry", source: "broiler", unit: "~4.5 lb", price: 29.25, perLb: 6.5, lbs: 4.5, pop: 2.4, season: BIRD, par: 40, frozen: true, wholesale: true, yieldPer: 0.55 },
  { id: "chx-breast", name: "Chicken breast", category: "Poultry", enterprise: "poultry", source: "broiler", unit: "pkg, ~1.4 lb", price: 18.55, perLb: 13.25, lbs: 1.4, pop: 3, season: BIRD, par: 40, frozen: true, yieldPer: 0.45 },
  { id: "chx-thigh", name: "Chicken thighs", category: "Poultry", enterprise: "poultry", source: "broiler", unit: "pkg, ~1.5 lb", price: 13.5, perLb: 9, lbs: 1.5, pop: 1.5, season: BIRD, par: 30, frozen: true, yieldPer: 0.35 },
  { id: "chx-wings", name: "Chicken wings", category: "Poultry", enterprise: "poultry", source: "broiler", unit: "1 lb pkg", price: 8, perLb: 8, lbs: 1, pop: 1, season: BIRD, par: 20, frozen: true, yieldPer: 0.2 },
  { id: "turkey", name: "Thanksgiving turkey", category: "Turkey", enterprise: "poultry", source: "turkey", unit: "whole, fresh", price: 144.5, perLb: 8.5, lbs: 17, pop: 0, par: 0 },

  // Eggs
  { id: "eggs", name: "Pasture-raised eggs", category: "Eggs", enterprise: "eggs", source: "eggs", unit: "dozen", price: 8, lbs: 1.6, pop: 12, season: HOLIDAY, par: 260, wholesale: true },

  // Creamery
  { id: "milk-extra", name: "A2A2 raw milk, extra gallon", category: "Creamery", enterprise: "dairy", source: "milk", unit: "gallon (owners only)", price: 11, lbs: 8.6, pop: 3.2, par: 0, herdshareOnly: true },
  { id: "cream", name: "Raw cream", category: "Creamery", enterprise: "dairy", source: "cream", unit: "pint (owners only)", price: 8, lbs: 1, pop: 2, par: 0, herdshareOnly: true },
  { id: "butter", name: "Raw butter", category: "Creamery", enterprise: "dairy", source: "butter", unit: "8 oz", price: 12, perLb: 24, lbs: 0.5, pop: 4.2, season: HOLIDAY, par: 40, wholesale: true },
  { id: "ch-cheddar", name: "Aged raw-milk cheddar", category: "Creamery", enterprise: "dairy", source: "cheese", unit: "half-lb block", price: 6.5, perLb: 13, lbs: 0.5, pop: 5, season: HOLIDAY, par: 80, wholesale: true },
  { id: "ch-gouda", name: "Raw-milk gouda", category: "Creamery", enterprise: "dairy", source: "cheese", unit: "half-lb block", price: 6.5, perLb: 13, lbs: 0.5, pop: 3.8, season: HOLIDAY, par: 60, wholesale: true },
  { id: "ch-colby", name: "Raw-milk colby", category: "Creamery", enterprise: "dairy", source: "cheese", unit: "half-lb block", price: 6.5, perLb: 13, lbs: 0.5, pop: 2.8, par: 50, wholesale: true },
  { id: "ch-sheep", name: "Sheep cheddar", category: "Creamery", enterprise: "partner", source: "partner", unit: "half-lb block", price: 9, perLb: 18, lbs: 0.5, pop: 1, par: 24 },

  // Bone broth, bakery, pantry
  { id: "broth", name: "Beef bone broth", category: "Bone broth", enterprise: "beef", source: "broth", unit: "quart jar", price: 10, lbs: 2.2, pop: 2.8, season: STEW, par: 60, frozen: true, wholesale: true },
  { id: "bread-country", name: "Sweet Grass Sourdough, country loaf", category: "Sourdough", enterprise: "bakery", source: "bakery", unit: "loaf", price: 9, lbs: 1.5, pop: 6, par: 0, wholesale: true },
  { id: "bread-sandwich", name: "Sweet Grass Sourdough, sandwich loaf", category: "Sourdough", enterprise: "bakery", source: "bakery", unit: "loaf", price: 8, lbs: 1.4, pop: 2.6, par: 0, wholesale: true },
  { id: "soap", name: "Goat milk soap (partner)", category: "Pantry & partners", enterprise: "partner", source: "partner", unit: "bar", price: 7, lbs: 0.3, pop: 1, par: 40 },
  { id: "honey", name: "Raw wildflower honey (partner)", category: "Pantry & partners", enterprise: "partner", source: "partner", unit: "1 lb jar", price: 14, lbs: 1.3, pop: 1.4, par: 50, wholesale: true },
  { id: "maple", name: "Maple syrup (partner)", category: "Pantry & partners", enterprise: "partner", source: "partner", unit: "pint", price: 18, lbs: 1.5, pop: 1, season: HOLIDAY, par: 32, wholesale: true },
  { id: "ticket", name: "Farm Carnival ticket", category: "Events", enterprise: "events", source: "tickets", unit: "ticket", price: 15, lbs: 0, pop: 0, par: 0 },
];

const W = (standing: Record<string, number>) => standing;

export const sweetgrassSeed: FarmSeed = {
  acres: 140,
  established: 2013,
  chemicalFreeSince: 1991,
  people: [
    { id: "sam", name: "Sam Ostrander", role: "Farm manager", phone: "(740) 555-0111" },
    { id: "micah", name: "Micah Teller", role: "Herdsman", phone: "(740) 555-0112" },
    { id: "leah", name: "Leah Brandt", role: "Creamery & cheese", phone: "(740) 555-0113" },
    { id: "josie", name: "Josie Quill", role: "Poultry & eggs", phone: "(740) 555-0114" },
    { id: "tess", name: "Tess Varga", role: "Farm store & orders", phone: "(740) 555-0115" },
    { id: "mara", name: "Mara Lind", role: "Bakery", phone: "(740) 555-0116" },
    { id: "ben", name: "Ben Arno", role: "Delivery driver", phone: "(740) 555-0117" },
    { id: "owen", name: "Owen Pike", role: "Delivery & wholesale", phone: "(740) 555-0118" },
  ],
  vet: { id: "vet", name: "Dr. Elaine Corwin, DVM", role: "Large-animal vet (Valley Large Animal Clinic)", phone: "(740) 555-0142" },
  processor: { id: "proc", name: "Brightwater Custom Meats", role: "USDA processor (beef, pork, lamb)", phone: "(740) 555-0156" },
  lab: { id: "lab", name: "Tri-County Dairy Lab", role: "Third-party milk testing", phone: "(614) 555-0163" },
  skus,
  zones: [
    { id: "z-wc", name: "Worthington & Clintonville", day: 2, driver: "ben", miles: 118 },
    { id: "z-wp", name: "Westerville & Polaris", day: 2, driver: "ben", miles: 104 },
    { id: "z-dh", name: "Dublin & Hilliard", day: 4, driver: "ben", miles: 132 },
    { id: "z-ug", name: "Upper Arlington & Grandview", day: 4, driver: "ben", miles: 126 },
    { id: "z-bg", name: "Bexley & German Village", day: 6, driver: "owen", miles: 128 },
    { id: "z-ng", name: "New Albany & Gahanna", day: 6, driver: "owen", miles: 112 },
  ],
  sites: [
    { id: "s-farm", name: "The farm store", town: "Fredericktown", day: 5, host: "Farm store counter" },
    { id: "s-mv", name: "Mount Vernon pickup", town: "Mount Vernon", day: 3, host: "Garage host on Elm St." },
    { id: "s-del", name: "Delaware pickup", town: "Delaware", day: 4, host: "Church lot host" },
    { id: "s-sun", name: "Sunbury pickup", town: "Sunbury", day: 6, host: "Porch host off the square" },
  ],
  wholesale: [
    { id: "w01", name: "Little Pine Grocery", type: "Retail store", town: "Worthington", contact: "Dana Whitfield", day: 2, every: 1, since: -30, standing: W({ eggs: 10, "ch-cheddar": 12, "ch-gouda": 8, butter: 6, "beef-ground": 20, broth: 12 }) },
    { id: "w02", name: "Old Mill Co-op", type: "Retail store", town: "Mount Vernon", contact: "Grant Ellery", day: 3, every: 1, since: -40, standing: W({ eggs: 12, "ch-cheddar": 10, "ch-colby": 8, "beef-ground": 25, "pork-bacon": 10, honey: 6 }) },
    { id: "w03", name: "Harvest Lantern Market", type: "Retail store", town: "Delaware", contact: "Priya Holcomb", day: 4, every: 1, since: -26, standing: W({ eggs: 8, "ch-gouda": 8, "beef-ground": 15, broth: 8, "bread-country": 8 }) },
    { id: "w04", name: "Kettle Hill Provisions", type: "Retail store", town: "Clintonville", contact: "Marcus Bell", day: 2, every: 2, since: -18, standing: W({ eggs: 7, "ch-cheddar": 10, butter: 6, "beef-stew": 8, "pork-sausage": 10 }) },
    { id: "w05", name: "Bramble & Root Grocer", type: "Retail store", town: "Granville", contact: "Ivy Castellano", day: 3, every: 2, since: -22, standing: W({ eggs: 8, "ch-cheddar": 8, "ch-colby": 6, honey: 6, maple: 4 }) },
    { id: "w06", name: "Corner Pantry Natural Foods", type: "Retail store", town: "Westerville", contact: "Russ Delaney", day: 2, every: 1, since: 4, standing: W({ eggs: 6, "beef-ground": 15, broth: 10, "ch-gouda": 6 }) },
    { id: "w07", name: "Fieldstone Market", type: "Retail store", town: "Dublin", contact: "Celeste Romero", day: 4, every: 2, since: -14, standing: W({ eggs: 8, "beef-ground": 20, "pork-bacon": 8, "chx-whole": 6 }) },
    { id: "w08", name: "Two Rivers Mercantile", type: "Retail store", town: "Mount Vernon", contact: "Hollis Grady", day: 3, every: 2, since: -9, standing: W({ eggs: 5, "ch-cheddar": 6, honey: 4, maple: 4 }), lapsedDaysAgo: 52 },
    { id: "w09", name: "Northwood Natural Grocer", type: "Retail store", town: "Upper Arlington", contact: "Naomi Trent", day: 4, every: 1, since: 8, standing: W({ eggs: 7, "ch-cheddar": 8, butter: 4, "beef-ground": 12 }) },
    { id: "w10", name: "Juniper & Rye", type: "Restaurant", town: "Columbus", contact: "Chef Anton Reyes", day: 4, every: 1, since: -30, standing: W({ "beef-ground": 25, "beef-ribeye": 8, "beef-strip": 6, eggs: 6, "pork-bacon": 8 }) },
    { id: "w11", name: "Copper Kettle Bistro", type: "Restaurant", town: "Granville", contact: "Rachel Moen", day: 3, every: 1, since: -24, standing: W({ "beef-ground": 20, "beef-shortrib": 6, eggs: 4, "chx-whole": 6 }) },
    { id: "w12", name: "The Hayloft Table", type: "Restaurant", town: "Delaware", contact: "Theo Varnes", day: 4, every: 1, since: -20, standing: W({ "beef-ground": 18, "pork-chops": 10, eggs: 5, "ch-cheddar": 6 }) },
    { id: "w13", name: "Ember & Oak", type: "Restaurant", town: "Worthington", contact: "Chef Lena Park", day: 2, every: 1, since: -16, standing: W({ "beef-ribeye": 10, "beef-strip": 8, "beef-ground": 15, "pork-bacon": 6 }) },
    { id: "w14", name: "Larkspur Kitchen", type: "Restaurant", town: "German Village", contact: "Omar Haddad", day: 4, every: 2, since: -12, standing: W({ "beef-ground": 15, eggs: 5, "chx-whole": 8, butter: 4 }) },
    { id: "w15", name: "Gristmill Tavern", type: "Restaurant", town: "Mount Vernon", contact: "Wade Lambert", day: 3, every: 1, since: -28, standing: W({ "beef-ground": 30, "pork-sausage": 10, eggs: 6 }) },
    { id: "w16", name: "Saltbox Supper Club", type: "Restaurant", town: "Bexley", contact: "Fiona Marsh", day: 2, every: 2, since: 2, standing: W({ "beef-ribeye": 6, "beef-shortrib": 6, "pork-chops": 8, "lamb-chops": 4 }) },
    { id: "w17", name: "Wildflower Trattoria", type: "Restaurant", town: "Clintonville", contact: "Gino Albrecht", day: 2, every: 1, since: 10, standing: W({ "beef-ground": 15, eggs: 6, "ch-gouda": 4 }) },
    { id: "w18", name: "Hearthside Café", type: "Café", town: "Fredericktown", contact: "Bonnie Kessler", day: 3, every: 1, since: -36, standing: W({ eggs: 6, "bread-country": 10, butter: 4, "pork-sausage": 6 }) },
    { id: "w19", name: "Morning Field Coffee", type: "Café", town: "Mount Vernon", contact: "Jules Ahn", day: 3, every: 1, since: -15, standing: W({ eggs: 4, "bread-country": 8, "ch-cheddar": 4 }) },
    { id: "w20", name: "Sparrow Bakehouse Café", type: "Café", town: "Delaware", contact: "Tamsin Ray", day: 4, every: 1, since: -11, standing: W({ eggs: 5, butter: 6, "bread-sandwich": 6 }) },
    { id: "w21", name: "Blue Heron Coffee", type: "Café", town: "Worthington", contact: "Eddie Novak", day: 2, every: 2, since: 6, standing: W({ eggs: 4, "bread-country": 6 }) },
    { id: "w22", name: "Meadowlark Café", type: "Café", town: "Westerville", contact: "Simone Clark", day: 2, every: 1, since: 11, standing: W({ eggs: 4, "bread-sandwich": 6, butter: 3 }) },
    { id: "w23", name: "Village Green Farm Market", type: "Market", town: "Granville", contact: "Pete Sorensen", day: 3, every: 1, since: -33, standing: W({ eggs: 8, "ch-cheddar": 10, honey: 6, maple: 4, "beef-ground": 15 }) },
    { id: "w24", name: "Riverside Farm Stand", type: "Market", town: "Gambier", contact: "Lucy Andersen", day: 3, every: 2, since: -20, standing: W({ eggs: 6, "ch-colby": 6, "beef-ground": 10 }) },
    { id: "w25", name: "Crossroads Market Co-op", type: "Market", town: "Sunbury", contact: "Marla Fitch", day: 4, every: 2, since: -7, standing: W({ eggs: 6, "ch-gouda": 6, "pork-bacon": 6, broth: 6 }) },
  ],
  paddocks: [
    { id: "p01", name: "North Ridge", use: "rotation" },
    { id: "p02", name: "Spring Run", use: "rotation" },
    { id: "p03", name: "Windmill", use: "rotation" },
    { id: "p04", name: "Big Field", use: "hay" },
    { id: "p05", name: "Orchard", use: "rotation" },
    { id: "p06", name: "Lane East", use: "rotation" },
    { id: "p07", name: "Pond Field", use: "rotation" },
    { id: "p08", name: "Lane West", use: "rotation" },
    { id: "p09", name: "Hickory", use: "rotation" },
    { id: "p10", name: "Back Forty", use: "stockpile" },
    { id: "p11", name: "Sugarbush", use: "rotation" },
    { id: "p12", name: "School Lot", use: "rotation" },
    { id: "p13", name: "Creek Bottom", use: "stockpile" },
    { id: "p14", name: "Sunset", use: "rotation" },
  ],
  cowNames: [
    "Clover", "Marigold", "Juniper", "Hazel", "Buttercup", "Willow", "Poppy", "Maple", "Daisy", "Ivy", "Fern", "Honey", "Primrose", "Olive",
    "Bluebell", "Sorrel", "Tansy", "Nutmeg", "Ginger", "Pearl", "Rosie", "Belle", "Opal", "Clementine", "Magnolia", "Saffron", "Wren", "Pippa",
    "Dottie", "Mabel", "Birdie", "Fiona", "Hattie", "Lulu", "Peaches", "Tilly", "Winnie", "Biscuit", "Cocoa", "Freckles", "Goldie", "Minnie",
    "Pumpkin", "Sage", "Tulip", "Violet", "Yarrow", "Zinnia", "Aster", "Briar", "Cricket", "Dahlia", "Echo", "Flora", "Gemma",
  ],
  breeds: [
    { name: "Jersey", share: 0.48 },
    { name: "Jersey × Normande", share: 0.2 },
    { name: "Guernsey", share: 0.17 },
    { name: "Milking Shorthorn", share: 0.15 },
  ],
  equipment: [
    { id: "e-milk", name: "Milking system (bucket units + vacuum pump)", group: "Dairy", every: 30, task: "Replace inflations, check vacuum level", cost: 140 },
    { id: "e-tank", name: "Bulk tank (600 gal)", group: "Dairy", every: 90, task: "Compressor service, wash-system check", cost: 260 },
    { id: "e-vat", name: "Cheese vat + press", group: "Creamery", every: 90, task: "Gasket + valve inspection", cost: 90 },
    { id: "e-cooler", name: "Walk-in cooler", group: "Cold storage", every: 60, task: "Clean coils, log temps", cost: 120 },
    { id: "e-freezer", name: "Walk-in freezer", group: "Cold storage", every: 60, task: "Defrost check, door seals", cost: 150 },
    { id: "e-chest", name: "Farm store chest freezers (4)", group: "Cold storage", every: 90, task: "Defrost + seal check", cost: 40 },
    { id: "e-oven", name: "Bakery deck oven", group: "Bakery", every: 90, task: "Burner + stone inspection", cost: 110 },
    { id: "e-trac1", name: "Utility tractor (75 hp)", group: "Field", every: 120, task: "250-hour oil, filters, hydraulics", cost: 420 },
    { id: "e-trac2", name: "Compact tractor", group: "Field", every: 150, task: "Oil, filters, grease", cost: 210 },
    { id: "e-skid", name: "Skid steer", group: "Field", every: 120, task: "Oil, grease, track tension", cost: 260 },
    { id: "e-hay", name: "Hay mower, rake + baler", group: "Field", every: 365, task: "Pre-season knives, belts, bearings", cost: 680 },
    { id: "e-fn", name: "Fence energizer, north", group: "Fencing", every: 30, task: "Voltage test, ground rods", cost: 0 },
    { id: "e-fs", name: "Fence energizer, south", group: "Fencing", every: 30, task: "Voltage test, ground rods", cost: 0 },
    { id: "e-water", name: "Pasture water lines + tanks", group: "Fencing", every: 30, task: "Float valves, line leaks", cost: 35 },
    { id: "e-van1", name: "Delivery van 1 (refrigerated)", group: "Delivery", every: 90, task: "Oil, tires, reefer unit check", cost: 310 },
    { id: "e-van2", name: "Delivery van 2 (refrigerated)", group: "Delivery", every: 90, task: "Oil, tires, reefer unit check", cost: 310 },
    { id: "e-egg1", name: "Eggmobile 1", group: "Poultry", every: 45, task: "Nest boxes, axle, waterers", cost: 25 },
    { id: "e-egg2", name: "Eggmobile 2", group: "Poultry", every: 45, task: "Nest boxes, axle, waterers", cost: 25 },
    { id: "e-egg3", name: "Eggmobile 3", group: "Poultry", every: 45, task: "Nest boxes, axle, waterers", cost: 25 },
    { id: "e-shelters", name: "Broiler shelters (6)", group: "Poultry", every: 60, task: "Tarps, wheels, feeders", cost: 60 },
    { id: "e-gen", name: "Standby generator", group: "Dairy", every: 90, task: "Load test, oil", cost: 180 },
  ],
  repairs: [
    { equipment: "e-milk", title: "Replaced pulsator on unit 3", cost: 186 },
    { equipment: "e-tank", title: "Agitator motor bearing", cost: 412 },
    { equipment: "e-cooler", title: "Door closer replaced", cost: 96 },
    { equipment: "e-freezer", title: "Evaporator fan motor", cost: 338 },
    { equipment: "e-trac1", title: "Hydraulic hose on loader", cost: 145 },
    { equipment: "e-skid", title: "Left drive chain adjusted", cost: 80 },
    { equipment: "e-hay", title: "Baler pickup tines (12)", cost: 220 },
    { equipment: "e-fn", title: "Lightning arrestor after storm", cost: 64 },
    { equipment: "e-water", title: "Split line at Pond Field", cost: 48 },
    { equipment: "e-van1", title: "Reefer belt + recharge", cost: 465 },
    { equipment: "e-van2", title: "Rear brake pads", cost: 290 },
    { equipment: "e-egg2", title: "Rebuilt ramp hinge", cost: 38 },
    { equipment: "e-oven", title: "Igniter replaced", cost: 154 },
    { equipment: "e-shelters", title: "New tarps on 2 shelters", cost: 132 },
  ],
  boards: [
    { id: "barn", name: "Farm Store Barn Conversion", items: [
      { name: "Final electrical inspection", owner: "sam", status: "Working on it", priority: "High", start: -6, due: 5 },
      { name: "Pour concrete for cooler pad", owner: "sam", status: "Done", priority: "High", start: -40, due: -26 },
      { name: "Walk-in cooler delivery + install", owner: "sam", status: "Stuck", priority: "High", start: -3, due: 12 },
      { name: "Shelving and checkout counter", owner: "tess", status: "Not started", priority: "Medium", start: 10, due: 24 },
      { name: "Signage + hours on the road sign", owner: "tess", status: "Not started", priority: "Low", start: 18, due: 30 },
      { name: "Move POS + card reader from old store", owner: "tess", status: "Not started", priority: "Medium", start: 25, due: 33 },
      { name: "Health department walkthrough", owner: "sam", status: "Not started", priority: "High", start: 26, due: 36 },
    ] },
    { id: "bundles", name: "Fall Freezer Bundle Launch", items: [
      { name: "Finalize bundle contents + pricing", owner: "tess", status: "Done", priority: "High", start: -30, due: -21 },
      { name: "Photograph bundles for the store", owner: "tess", status: "Done", priority: "Medium", start: -22, due: -16 },
      { name: "Email herdshare owners first (Drip)", owner: "tess", status: "Done", priority: "High", start: -14, due: -10 },
      { name: "Book extra processing slot for November", owner: "sam", status: "Working on it", priority: "High", start: -5, due: 4 },
      { name: "Pre-pack 40 bundles before Field Day rush", owner: "tess", status: "Working on it", priority: "Medium", start: -2, due: 6 },
      { name: "Restock jerky + snack sticks", owner: "sam", status: "Stuck", priority: "Medium", start: -8, due: 9 },
    ] },
    { id: "turkeys", name: "Thanksgiving Turkeys", items: [
      { name: "Open pre-orders + deposits", owner: "tess", status: "Done", priority: "High", start: -66, due: -60 },
      { name: "Size-mix check vs. pre-orders", owner: "josie", status: "Working on it", priority: "Medium", start: -4, due: 8 },
      { name: "Confirm processing crew + day", owner: "josie", status: "Working on it", priority: "High", start: -10, due: 14 },
      { name: "Order turkey bags + labels", owner: "tess", status: "Not started", priority: "Medium", start: 7, due: 21 },
      { name: "Pickup schedule email", owner: "tess", status: "Not started", priority: "High", start: 30, due: 40 },
    ] },
    { id: "fielddays", name: "Farm Field Days", items: [
      { name: "October Field Day wrap-up + photos", owner: "tess", status: "Working on it", priority: "Low", start: -2, due: 4 },
      { name: "Thank-you email to visitors", owner: "tess", status: "Not started", priority: "Medium", start: 1, due: 5 },
      { name: "Hayride wagon repairs", owner: "sam", status: "Not started", priority: "Low", start: 20, due: 60 },
      { name: "June Field Day vendor list", owner: "tess", status: "Not started", priority: "Low", start: 90, due: 150 },
    ] },
    { id: "renewals", name: "Herdshare Renewals", items: [
      { name: "Send renewal reminders (30-day)", owner: "tess", status: "Working on it", priority: "High", start: -3, due: 3 },
      { name: "Chase missing agreements", owner: "tess", status: "Stuck", priority: "High", start: -12, due: 2 },
      { name: "Update boarding-fee invoices in QuickBooks", owner: "tess", status: "Not started", priority: "Medium", start: 2, due: 9 },
      { name: "Waitlist: offer open shares", owner: "tess", status: "Not started", priority: "Medium", start: 6, due: 16 },
    ] },
    { id: "cheese", name: "New Cheese Flavors", items: [
      { name: "Test batch: garlic-chive colby", owner: "leah", status: "Done", priority: "Medium", start: -50, due: -40 },
      { name: "Test batch: smoked gouda", owner: "leah", status: "Working on it", priority: "Medium", start: -20, due: 25 },
      { name: "Tasting panel with herdshare owners", owner: "leah", status: "Not started", priority: "Low", start: 30, due: 45 },
      { name: "Label + lot-code template", owner: "leah", status: "Not started", priority: "Low", start: 35, due: 50 },
    ] },
  ],
  chores: [
    { time: "5:00", task: "Milking + parlor wash-down", owner: "micah", area: "Dairy" },
    { time: "6:15", task: "Bulk tank temp + chart", owner: "micah", area: "Dairy" },
    { time: "6:30", task: "Feed calves", owner: "micah", area: "Dairy" },
    { time: "7:00", task: "Move eggmobiles behind the herd", owner: "josie", area: "Poultry" },
    { time: "7:30", task: "Check waterers + fence voltage", owner: "sam", area: "Pasture" },
    { time: "8:00", task: "Egg collection, round 1", owner: "josie", area: "Poultry" },
    { time: "9:00", task: "Pick + pack today's orders", owner: "tess", area: "Orders" },
    { time: "10:00", task: "Move herd to fresh strip", owner: "sam", area: "Pasture" },
    { time: "12:30", task: "Egg collection, round 2", owner: "josie", area: "Poultry" },
    { time: "14:00", task: "Wash, grade + carton eggs", owner: "josie", area: "Poultry" },
    { time: "16:30", task: "Move broiler shelters + feed", owner: "josie", area: "Poultry" },
    { time: "20:30", task: "Close out farm store", owner: "tess", area: "Orders" },
  ],
  names: {
    first: [
      "Megan", "Josh", "Rebecca", "Tyler", "Amanda", "Kyle", "Sarah", "Nathan", "Lauren", "Derek", "Kristen", "Aaron", "Brooke", "Caleb", "Jenna",
      "Dustin", "Heather", "Logan", "Allison", "Trevor", "Molly", "Evan", "Courtney", "Grant", "Bethany", "Luke", "Natalie", "Ryan", "Whitney",
      "Cody", "Erin", "Jordan", "Abby", "Sean", "Kelsey", "Brandon", "Hannah", "Mitch", "Leslie", "Adam", "Tara", "Paige", "Wes", "Gina",
      "Marco", "Anita", "Priya", "Devon", "Rosa", "Kenji", "Aisha", "Tomás", "Mei", "Darius", "Ingrid", "Farah", "Colin", "Nora", "Vince", "Joy",
    ],
    last: [
      "Albright", "Barlow", "Castell", "Dorsey", "Eberly", "Fenwick", "Galloway", "Hollis", "Imhoff", "Jessup", "Kessler", "Lindell", "Marsh",
      "Norwood", "Oakes", "Pruitt", "Quarles", "Ridley", "Stroud", "Tilton", "Upton", "Vance", "Wexler", "Yoder", "Zeller", "Ashby", "Brenner",
      "Calloway", "Delgado", "Ellison", "Fairbanks", "Grubb", "Haskins", "Ivers", "Jarvis", "Kowalski", "Lockhart", "McAllister", "Nakamura",
      "Ostrowski", "Pemberton", "Rasmussen", "Sorensen", "Thackery", "Underwood", "Vasquez", "Whitlock", "Abernathy", "Birch", "Coyle",
      "Dunmore", "Esposito", "Fairweather", "Gutierrez", "Hendrix", "Okafor", "Patel", "Quinlan", "Shah", "Tran",
    ],
  },
  towns: {
    delivery: {
      "z-wc": ["Worthington", "Clintonville"],
      "z-wp": ["Westerville", "Polaris"],
      "z-dh": ["Dublin", "Hilliard"],
      "z-ug": ["Upper Arlington", "Grandview Heights"],
      "z-bg": ["Bexley", "German Village"],
      "z-ng": ["New Albany", "Gahanna"],
    },
    pickup: {
      "s-farm": ["Fredericktown", "Mount Vernon", "Centerburg"],
      "s-mv": ["Mount Vernon", "Gambier"],
      "s-del": ["Delaware", "Powell"],
      "s-sun": ["Sunbury", "Galena"],
    },
  },
  notes: [
    "Leave cooler on the side porch, behind the bench.",
    "Prefers thick-cut ribeyes when we have them.",
    "Asked about liver for the dog. Happy to take seconds.",
    "Pays by card on file; likes a text the night before.",
    "Two kids, big on breakfast sausage and eggs.",
    "Wants to visit for Field Day with her book club.",
    "Allergic to nothing, picky about bacon thickness.",
    "Splits a Quarter-Share box with a neighbor.",
    "Gluten-sensitive: skip sourdough upsells.",
    "Gate code is in the GrazeCart delivery notes.",
    "Asked to be first call when raw butter is back.",
    "Teacher. Orders less over summer break.",
  ],
  tools: [
    { name: "GrazeCart", what: "Orders, customers + products", mode: "CSV import", minutesAgo: 47 },
    { name: "QuickBooks", what: "Sales, expenses + invoices", mode: "Nightly sync", minutesAgo: 318 },
    { name: "Drip", what: "Email lists + campaigns", mode: "Nightly sync", minutesAgo: 535 },
  ],
  herdshare: { pricePerGallon: 11, shareFee: 50 },
};
